### PR TITLE
Jenkins Build Fix?

### PR DESCRIPTION
**Pull request by TheKye**

### CODE REVIEW

**Comment by halkeye** [comment]
awesome. it builds. In theory if we tag it it should get deployed to mod.io

**Comment by TheKye** [comment]
Sounds good!

**Comment by halkeye** [comment]
released! thanks for helping out. I'm thinking i might spin up a server again next year

**Comment by TheKye** [comment]
Hey no problem! Yeah man, get back into it! see if it still strikes your fancy!

**Pull request merged**
